[credentials]
[google_api]
#This is copied from the OAth2 credentials in the google cloud console
SERVICE_ACCOUNT_FILE = " "

#This is inside the URL between the d/ and the /edit, about 40-50 characters cpy it and paste it here.
SHEET_ID = " "

#This is the name of the google sheets tab at the bottom of the google sheets page
RANGE = ''

[email]
#This is the email address that will send the emails
SENDER_EMAIL = ''

#This is the password for the email address
SENDER_PASSWORD = ''

#This is the email address of the recipient
RECEIVER_EMAIL = ''

[door]
DOOR_LOCATION